[project]
name = "{{cookiecutter.dir_name}}"
version = "25.1"
description = "{{cookiecutter.description}}"
readme = "README.md"

dependencies = []

[dependency-groups]
dev = ["pytest", "ruff", "mypy"]

[build-system]
requires = ["setuptools >= 64.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
