/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Tectonic API
 * The Tectonic API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { useCallback } from 'react';

import { useCustomAxiosInstance } from './instance';
import type { ErrorType, BodyType } from './instance';
export interface LoginRequest {
  /** The users email */
  username: string;
  /** The users password */
  password: string;
}

export interface LoginResponse {
  /** The users access token */
  access_token: string;
  /** The users email */
  username: string;
}

export interface ProfileResponse {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  createdAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  updatedAt: string;
}

/**
 * @nullable
 */
export type ProfileMaritalStatus =
  | (typeof ProfileMaritalStatus)[keyof typeof ProfileMaritalStatus]
  | null;

export const ProfileMaritalStatus = {
  SINGLE: 'SINGLE',
  MARRIED: 'MARRIED',
  PARTNERED: 'PARTNERED',
  DIVORCED: 'DIVORCED',
  WIDOWED: 'WIDOWED',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type ProfileHousingStatus =
  | (typeof ProfileHousingStatus)[keyof typeof ProfileHousingStatus]
  | null;

export const ProfileHousingStatus = {
  OWNER_OUTRIGHT: 'OWNER_OUTRIGHT',
  OWNER_WITH_MORTGAGE: 'OWNER_WITH_MORTGAGE',
  RENTER: 'RENTER',
  LIVING_WITH_FAMILY: 'LIVING_WITH_FAMILY',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type ProfileEmploymentStatus =
  | (typeof ProfileEmploymentStatus)[keyof typeof ProfileEmploymentStatus]
  | null;

export const ProfileEmploymentStatus = {
  EMPLOYED: 'EMPLOYED',
  SELF_EMPLOYED: 'SELF_EMPLOYED',
  UNEMPLOYED: 'UNEMPLOYED',
  STUDENT: 'STUDENT',
  RETIRED: 'RETIRED',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type ProfileFinancialLiteracy =
  | (typeof ProfileFinancialLiteracy)[keyof typeof ProfileFinancialLiteracy]
  | null;

export const ProfileFinancialLiteracy = {
  LOW: 'LOW',
  DEVELOPING: 'DEVELOPING',
  CAPABLE: 'CAPABLE',
  EXPERT: 'EXPERT',
} as const;

/**
 * @nullable
 */
export type ProfileRiskTolerance =
  | (typeof ProfileRiskTolerance)[keyof typeof ProfileRiskTolerance]
  | null;

export const ProfileRiskTolerance = {
  CONSERVATIVE: 'CONSERVATIVE',
  MODERATE: 'MODERATE',
  BALANCED: 'BALANCED',
  GROWTH: 'GROWTH',
  AGGRESSIVE: 'AGGRESSIVE',
} as const;

export type ProfileGoalsItem =
  (typeof ProfileGoalsItem)[keyof typeof ProfileGoalsItem];

export const ProfileGoalsItem = {
  EMERGENCY_FUND: 'EMERGENCY_FUND',
  REDUCE_SPENDING: 'REDUCE_SPENDING',
  REDUCE_DEBT: 'REDUCE_DEBT',
  BUY_HOME: 'BUY_HOME',
  RETIREMENT: 'RETIREMENT',
  EDUCATION: 'EDUCATION',
  GROW_INVESTMENTS: 'GROW_INVESTMENTS',
  PROTECT_INCOME: 'PROTECT_INCOME',
} as const;

export type ProfileServiceInterestsItem =
  (typeof ProfileServiceInterestsItem)[keyof typeof ProfileServiceInterestsItem];

export const ProfileServiceInterestsItem = {
  SAVINGS: 'SAVINGS',
  INSURANCE: 'INSURANCE',
  BROKER: 'BROKER',
  INVESTING: 'INVESTING',
  PENSION: 'PENSION',
  CREDIT: 'CREDIT',
  FINANCIAL_COACHING: 'FINANCIAL_COACHING',
} as const;

export interface Profile {
  id: string;
  firstName: string;
  lastName: string;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  dateOfBirth: string | null;
  /**
   * @nullable
   * @pattern ^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  customerReference: string | null;
  /** @nullable */
  maritalStatus: ProfileMaritalStatus;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  dependentCount: number;
  /** @nullable */
  street: string | null;
  /** @nullable */
  city: string | null;
  /** @nullable */
  postalCode: string | null;
  /** @nullable */
  country: string | null;
  /** @nullable */
  housingStatus: ProfileHousingStatus;
  /** @nullable */
  monthlyHousingCost: number | null;
  /** @nullable */
  employmentStatus: ProfileEmploymentStatus;
  /** @nullable */
  occupation: string | null;
  /** @nullable */
  employer: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  employmentStartDate: string | null;
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency: string;
  /** @nullable */
  monthlyNetIncome: number | null;
  /** @nullable */
  otherMonthlyIncome: number | null;
  /** @nullable */
  financialLiteracy: ProfileFinancialLiteracy;
  /** @nullable */
  riskTolerance: ProfileRiskTolerance;
  goals: ProfileGoalsItem[];
  serviceInterests: ProfileServiceInterestsItem[];
  /** @nullable */
  monthlyEssentialExpenses: number | null;
  /** @nullable */
  monthlyDiscretionaryExpenses: number | null;
  /** @nullable */
  monthlySavingsTarget: number | null;
  /** @nullable */
  liquidSavings: number | null;
  /** @nullable */
  investmentBalance: number | null;
  /** @nullable */
  pensionBalance: number | null;
  /** @nullable */
  realEstateValue: number | null;
  /** @nullable */
  mortgageBalance: number | null;
  /** @nullable */
  consumerDebtBalance: number | null;
  /** @nullable */
  otherDebtBalance: number | null;
  /** @nullable */
  hasLifeInsurance: boolean | null;
  /** @nullable */
  hasHomeInsurance: boolean | null;
  /** @nullable */
  hasHealthInsurance: boolean | null;
  /** @nullable */
  hasBrokerageAccount: boolean | null;
  /** @nullable */
  notes: string | null;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  createdAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  updatedAt: string;
}

export interface OffsetPaginatedProfiles {
  data: Profile[];
  total: number;
  pageIndex: number;
  pageSize: number;
  totalPages: number;
}

/**
 * @nullable
 */
export type CreateProfileRequestMaritalStatus =
  | (typeof CreateProfileRequestMaritalStatus)[keyof typeof CreateProfileRequestMaritalStatus]
  | null;

export const CreateProfileRequestMaritalStatus = {
  SINGLE: 'SINGLE',
  MARRIED: 'MARRIED',
  PARTNERED: 'PARTNERED',
  DIVORCED: 'DIVORCED',
  WIDOWED: 'WIDOWED',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type CreateProfileRequestHousingStatus =
  | (typeof CreateProfileRequestHousingStatus)[keyof typeof CreateProfileRequestHousingStatus]
  | null;

export const CreateProfileRequestHousingStatus = {
  OWNER_OUTRIGHT: 'OWNER_OUTRIGHT',
  OWNER_WITH_MORTGAGE: 'OWNER_WITH_MORTGAGE',
  RENTER: 'RENTER',
  LIVING_WITH_FAMILY: 'LIVING_WITH_FAMILY',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type CreateProfileRequestEmploymentStatus =
  | (typeof CreateProfileRequestEmploymentStatus)[keyof typeof CreateProfileRequestEmploymentStatus]
  | null;

export const CreateProfileRequestEmploymentStatus = {
  EMPLOYED: 'EMPLOYED',
  SELF_EMPLOYED: 'SELF_EMPLOYED',
  UNEMPLOYED: 'UNEMPLOYED',
  STUDENT: 'STUDENT',
  RETIRED: 'RETIRED',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type CreateProfileRequestFinancialLiteracy =
  | (typeof CreateProfileRequestFinancialLiteracy)[keyof typeof CreateProfileRequestFinancialLiteracy]
  | null;

export const CreateProfileRequestFinancialLiteracy = {
  LOW: 'LOW',
  DEVELOPING: 'DEVELOPING',
  CAPABLE: 'CAPABLE',
  EXPERT: 'EXPERT',
} as const;

/**
 * @nullable
 */
export type CreateProfileRequestRiskTolerance =
  | (typeof CreateProfileRequestRiskTolerance)[keyof typeof CreateProfileRequestRiskTolerance]
  | null;

export const CreateProfileRequestRiskTolerance = {
  CONSERVATIVE: 'CONSERVATIVE',
  MODERATE: 'MODERATE',
  BALANCED: 'BALANCED',
  GROWTH: 'GROWTH',
  AGGRESSIVE: 'AGGRESSIVE',
} as const;

export type CreateProfileRequestGoalsItem =
  (typeof CreateProfileRequestGoalsItem)[keyof typeof CreateProfileRequestGoalsItem];

export const CreateProfileRequestGoalsItem = {
  EMERGENCY_FUND: 'EMERGENCY_FUND',
  REDUCE_SPENDING: 'REDUCE_SPENDING',
  REDUCE_DEBT: 'REDUCE_DEBT',
  BUY_HOME: 'BUY_HOME',
  RETIREMENT: 'RETIREMENT',
  EDUCATION: 'EDUCATION',
  GROW_INVESTMENTS: 'GROW_INVESTMENTS',
  PROTECT_INCOME: 'PROTECT_INCOME',
} as const;

export type CreateProfileRequestServiceInterestsItem =
  (typeof CreateProfileRequestServiceInterestsItem)[keyof typeof CreateProfileRequestServiceInterestsItem];

export const CreateProfileRequestServiceInterestsItem = {
  SAVINGS: 'SAVINGS',
  INSURANCE: 'INSURANCE',
  BROKER: 'BROKER',
  INVESTING: 'INVESTING',
  PENSION: 'PENSION',
  CREDIT: 'CREDIT',
  FINANCIAL_COACHING: 'FINANCIAL_COACHING',
} as const;

export interface CreateProfileRequest {
  firstName: string;
  lastName: string;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  dateOfBirth?: string | null;
  /**
   * @nullable
   * @pattern ^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  customerReference?: string | null;
  /** @nullable */
  maritalStatus?: CreateProfileRequestMaritalStatus;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  dependentCount?: number;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  housingStatus?: CreateProfileRequestHousingStatus;
  /** @nullable */
  monthlyHousingCost?: number | null;
  /** @nullable */
  employmentStatus?: CreateProfileRequestEmploymentStatus;
  /** @nullable */
  occupation?: string | null;
  /** @nullable */
  employer?: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  employmentStartDate?: string | null;
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /** @nullable */
  monthlyNetIncome?: number | null;
  /** @nullable */
  otherMonthlyIncome?: number | null;
  /** @nullable */
  financialLiteracy?: CreateProfileRequestFinancialLiteracy;
  /** @nullable */
  riskTolerance?: CreateProfileRequestRiskTolerance;
  goals?: CreateProfileRequestGoalsItem[];
  serviceInterests?: CreateProfileRequestServiceInterestsItem[];
  /** @nullable */
  monthlyEssentialExpenses?: number | null;
  /** @nullable */
  monthlyDiscretionaryExpenses?: number | null;
  /** @nullable */
  monthlySavingsTarget?: number | null;
  /** @nullable */
  liquidSavings?: number | null;
  /** @nullable */
  investmentBalance?: number | null;
  /** @nullable */
  pensionBalance?: number | null;
  /** @nullable */
  realEstateValue?: number | null;
  /** @nullable */
  mortgageBalance?: number | null;
  /** @nullable */
  consumerDebtBalance?: number | null;
  /** @nullable */
  otherDebtBalance?: number | null;
  /** @nullable */
  hasLifeInsurance?: boolean | null;
  /** @nullable */
  hasHomeInsurance?: boolean | null;
  /** @nullable */
  hasHealthInsurance?: boolean | null;
  /** @nullable */
  hasBrokerageAccount?: boolean | null;
  /** @nullable */
  notes?: string | null;
}

/**
 * @nullable
 */
export type UpdateProfileRequestMaritalStatus =
  | (typeof UpdateProfileRequestMaritalStatus)[keyof typeof UpdateProfileRequestMaritalStatus]
  | null;

export const UpdateProfileRequestMaritalStatus = {
  SINGLE: 'SINGLE',
  MARRIED: 'MARRIED',
  PARTNERED: 'PARTNERED',
  DIVORCED: 'DIVORCED',
  WIDOWED: 'WIDOWED',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type UpdateProfileRequestHousingStatus =
  | (typeof UpdateProfileRequestHousingStatus)[keyof typeof UpdateProfileRequestHousingStatus]
  | null;

export const UpdateProfileRequestHousingStatus = {
  OWNER_OUTRIGHT: 'OWNER_OUTRIGHT',
  OWNER_WITH_MORTGAGE: 'OWNER_WITH_MORTGAGE',
  RENTER: 'RENTER',
  LIVING_WITH_FAMILY: 'LIVING_WITH_FAMILY',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type UpdateProfileRequestEmploymentStatus =
  | (typeof UpdateProfileRequestEmploymentStatus)[keyof typeof UpdateProfileRequestEmploymentStatus]
  | null;

export const UpdateProfileRequestEmploymentStatus = {
  EMPLOYED: 'EMPLOYED',
  SELF_EMPLOYED: 'SELF_EMPLOYED',
  UNEMPLOYED: 'UNEMPLOYED',
  STUDENT: 'STUDENT',
  RETIRED: 'RETIRED',
  OTHER: 'OTHER',
} as const;

/**
 * @nullable
 */
export type UpdateProfileRequestFinancialLiteracy =
  | (typeof UpdateProfileRequestFinancialLiteracy)[keyof typeof UpdateProfileRequestFinancialLiteracy]
  | null;

export const UpdateProfileRequestFinancialLiteracy = {
  LOW: 'LOW',
  DEVELOPING: 'DEVELOPING',
  CAPABLE: 'CAPABLE',
  EXPERT: 'EXPERT',
} as const;

/**
 * @nullable
 */
export type UpdateProfileRequestRiskTolerance =
  | (typeof UpdateProfileRequestRiskTolerance)[keyof typeof UpdateProfileRequestRiskTolerance]
  | null;

export const UpdateProfileRequestRiskTolerance = {
  CONSERVATIVE: 'CONSERVATIVE',
  MODERATE: 'MODERATE',
  BALANCED: 'BALANCED',
  GROWTH: 'GROWTH',
  AGGRESSIVE: 'AGGRESSIVE',
} as const;

export type UpdateProfileRequestGoalsItem =
  (typeof UpdateProfileRequestGoalsItem)[keyof typeof UpdateProfileRequestGoalsItem];

export const UpdateProfileRequestGoalsItem = {
  EMERGENCY_FUND: 'EMERGENCY_FUND',
  REDUCE_SPENDING: 'REDUCE_SPENDING',
  REDUCE_DEBT: 'REDUCE_DEBT',
  BUY_HOME: 'BUY_HOME',
  RETIREMENT: 'RETIREMENT',
  EDUCATION: 'EDUCATION',
  GROW_INVESTMENTS: 'GROW_INVESTMENTS',
  PROTECT_INCOME: 'PROTECT_INCOME',
} as const;

export type UpdateProfileRequestServiceInterestsItem =
  (typeof UpdateProfileRequestServiceInterestsItem)[keyof typeof UpdateProfileRequestServiceInterestsItem];

export const UpdateProfileRequestServiceInterestsItem = {
  SAVINGS: 'SAVINGS',
  INSURANCE: 'INSURANCE',
  BROKER: 'BROKER',
  INVESTING: 'INVESTING',
  PENSION: 'PENSION',
  CREDIT: 'CREDIT',
  FINANCIAL_COACHING: 'FINANCIAL_COACHING',
} as const;

export interface UpdateProfileRequest {
  firstName?: string;
  lastName?: string;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  dateOfBirth?: string | null;
  /**
   * @nullable
   * @pattern ^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  customerReference?: string | null;
  /** @nullable */
  maritalStatus?: UpdateProfileRequestMaritalStatus;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  dependentCount?: number;
  /** @nullable */
  street?: string | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  housingStatus?: UpdateProfileRequestHousingStatus;
  /** @nullable */
  monthlyHousingCost?: number | null;
  /** @nullable */
  employmentStatus?: UpdateProfileRequestEmploymentStatus;
  /** @nullable */
  occupation?: string | null;
  /** @nullable */
  employer?: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  employmentStartDate?: string | null;
  /**
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /** @nullable */
  monthlyNetIncome?: number | null;
  /** @nullable */
  otherMonthlyIncome?: number | null;
  /** @nullable */
  financialLiteracy?: UpdateProfileRequestFinancialLiteracy;
  /** @nullable */
  riskTolerance?: UpdateProfileRequestRiskTolerance;
  goals?: UpdateProfileRequestGoalsItem[];
  serviceInterests?: UpdateProfileRequestServiceInterestsItem[];
  /** @nullable */
  monthlyEssentialExpenses?: number | null;
  /** @nullable */
  monthlyDiscretionaryExpenses?: number | null;
  /** @nullable */
  monthlySavingsTarget?: number | null;
  /** @nullable */
  liquidSavings?: number | null;
  /** @nullable */
  investmentBalance?: number | null;
  /** @nullable */
  pensionBalance?: number | null;
  /** @nullable */
  realEstateValue?: number | null;
  /** @nullable */
  mortgageBalance?: number | null;
  /** @nullable */
  consumerDebtBalance?: number | null;
  /** @nullable */
  otherDebtBalance?: number | null;
  /** @nullable */
  hasLifeInsurance?: boolean | null;
  /** @nullable */
  hasHomeInsurance?: boolean | null;
  /** @nullable */
  hasHealthInsurance?: boolean | null;
  /** @nullable */
  hasBrokerageAccount?: boolean | null;
  /** @nullable */
  notes?: string | null;
}

export type HealthControllerCheck200Status =
  (typeof HealthControllerCheck200Status)[keyof typeof HealthControllerCheck200Status];

export const HealthControllerCheck200Status = {
  ok: 'ok',
  degraded: 'degraded',
} as const;

/**
 * @nullable
 */
export type HealthControllerCheck200Info = {
  [key: string]: {
    status: 'up' | 'degraded' | 'down';
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
} | null;

/**
 * @nullable
 */
export type HealthControllerCheck200Error = {
  [key: string]: {
    status: 'up' | 'degraded' | 'down';
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
} | null;

export type HealthControllerCheck200DetailsStatus =
  (typeof HealthControllerCheck200DetailsStatus)[keyof typeof HealthControllerCheck200DetailsStatus];

export const HealthControllerCheck200DetailsStatus = {
  up: 'up',
  degraded: 'degraded',
  down: 'down',
} as const;

export type HealthControllerCheck200Details = {
  [key: string]: {
    status: HealthControllerCheck200DetailsStatus;
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
};

export type HealthControllerCheck200 = {
  status?: HealthControllerCheck200Status;
  /** @nullable */
  info?: HealthControllerCheck200Info;
  /** @nullable */
  error?: HealthControllerCheck200Error;
  details?: HealthControllerCheck200Details;
};

export type HealthControllerCheck503Status =
  (typeof HealthControllerCheck503Status)[keyof typeof HealthControllerCheck503Status];

export const HealthControllerCheck503Status = {
  error: 'error',
  shutting_down: 'shutting_down',
} as const;

/**
 * @nullable
 */
export type HealthControllerCheck503Info = {
  [key: string]: {
    status: 'up' | 'degraded' | 'down';
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
} | null;

/**
 * @nullable
 */
export type HealthControllerCheck503Error = {
  [key: string]: {
    status: 'up' | 'degraded' | 'down';
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
} | null;

export type HealthControllerCheck503DetailsStatus =
  (typeof HealthControllerCheck503DetailsStatus)[keyof typeof HealthControllerCheck503DetailsStatus];

export const HealthControllerCheck503DetailsStatus = {
  up: 'up',
  degraded: 'degraded',
  down: 'down',
} as const;

export type HealthControllerCheck503Details = {
  [key: string]: {
    status: HealthControllerCheck503DetailsStatus;
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
};

export type HealthControllerCheck503 = {
  status?: HealthControllerCheck503Status;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};

export type ListProfilesParams = {
  /**
   * Page number (zero-based)
   */
  pageIndex?: number;
  /**
   * Number of records per page
   */
  pageSize?: number;
  /**
   * Sort order of results
   */
  order?: ListProfilesOrder;
  /**
   * Field to order results by
   */
  orderBy?: string;
};

export type ListProfilesOrder =
  (typeof ListProfilesOrder)[keyof typeof ListProfilesOrder];

export const ListProfilesOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const useAppControllerGetHelloHook = () => {
  const appControllerGetHello = useCustomAxiosInstance<void>();

  return useCallback(
    (signal?: AbortSignal) => {
      return appControllerGetHello({ url: `/api`, method: 'GET', signal });
    },
    [appControllerGetHello]
  );
};

export const getAppControllerGetHelloQueryKey = () => {
  return [`/api`] as const;
};

export const useAppControllerGetHelloQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetHelloQueryKey();

  const appControllerGetHello = useAppControllerGetHelloHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>
  > = ({ signal }) => appControllerGetHello(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerGetHelloQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>
>;
export type AppControllerGetHelloQueryError = ErrorType<unknown>;

export function useAppControllerGetHello<
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetHello<
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetHello<
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAppControllerGetHello<
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useAppControllerGetHelloQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const useHealthControllerCheckHook = () => {
  const healthControllerCheck =
    useCustomAxiosInstance<HealthControllerCheck200>();

  return useCallback(
    (signal?: AbortSignal) => {
      return healthControllerCheck({
        url: `/api/health`,
        method: 'GET',
        signal,
      });
    },
    [healthControllerCheck]
  );
};

export const getHealthControllerCheckQueryKey = () => {
  return [`/api/health`] as const;
};

export const useHealthControllerCheckQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  const healthControllerCheck = useHealthControllerCheckHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>
  > = ({ signal }) => healthControllerCheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthControllerCheckQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>
>;
export type HealthControllerCheckQueryError =
  ErrorType<HealthControllerCheck503>;

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useHealthControllerCheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Login
 */
export const useLoginHook = () => {
  const login = useCustomAxiosInstance<LoginResponse>();

  return useCallback(
    (loginRequest: BodyType<LoginRequest>, signal?: AbortSignal) => {
      return login({
        url: `/api/auth/login`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: loginRequest,
        signal,
      });
    },
    [login]
  );
};

export const useLoginMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  const mutationKey = ['login'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const login = useLoginHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
    { data: BodyType<LoginRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return login(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useLoginHook>>>
>;
export type LoginMutationBody = BodyType<LoginRequest>;
export type LoginMutationError = ErrorType<unknown>;

/**
 * @summary Login
 */
export const useLogin = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
      TError,
      { data: BodyType<LoginRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  return useMutation(useLoginMutationOptions(options), queryClient);
};

/**
 * @summary Get profile
 */
export const useGetProfileHook = () => {
  const getProfile = useCustomAxiosInstance<ProfileResponse>();

  return useCallback(
    (signal?: AbortSignal) => {
      return getProfile({ url: `/api/auth/profile`, method: 'GET', signal });
    },
    [getProfile]
  );
};

export const getGetProfileQueryKey = () => {
  return [`/api/auth/profile`] as const;
};

export const useGetProfileQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProfileQueryKey();

  const getProfile = useGetProfileHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>
  > = ({ signal }) => getProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProfileQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>
>;
export type GetProfileQueryError = ErrorType<void>;

export function useGetProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get profile
 */

export function useGetProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useGetProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary List profiles
 */
export const useListProfilesHook = () => {
  const listProfiles = useCustomAxiosInstance<OffsetPaginatedProfiles>();

  return useCallback(
    (params?: ListProfilesParams, signal?: AbortSignal) => {
      return listProfiles({
        url: `/api/profiles`,
        method: 'GET',
        params,
        signal,
      });
    },
    [listProfiles]
  );
};

export const getListProfilesQueryKey = (params?: ListProfilesParams) => {
  return [`/api/profiles`, ...(params ? [params] : [])] as const;
};

export const useListProfilesQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
  TError = ErrorType<void>,
>(
  params?: ListProfilesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListProfilesQueryKey(params);

  const listProfiles = useListProfilesHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>
  > = ({ signal }) => listProfiles(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListProfilesQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>
>;
export type ListProfilesQueryError = ErrorType<void>;

export function useListProfiles<
  TData = Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
  TError = ErrorType<void>,
>(
  params: undefined | ListProfilesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListProfiles<
  TData = Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
  TError = ErrorType<void>,
>(
  params?: ListProfilesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListProfiles<
  TData = Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
  TError = ErrorType<void>,
>(
  params?: ListProfilesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List profiles
 */

export function useListProfiles<
  TData = Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
  TError = ErrorType<void>,
>(
  params?: ListProfilesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useListProfilesHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useListProfilesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Create profile
 */
export const useCreateProfileHook = () => {
  const createProfile = useCustomAxiosInstance<Profile>();

  return useCallback(
    (
      createProfileRequest: BodyType<CreateProfileRequest>,
      signal?: AbortSignal
    ) => {
      return createProfile({
        url: `/api/profiles`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createProfileRequest,
        signal,
      });
    },
    [createProfile]
  );
};

export const useCreateProfileMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useCreateProfileHook>>>,
    TError,
    { data: BodyType<CreateProfileRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useCreateProfileHook>>>,
  TError,
  { data: BodyType<CreateProfileRequest> },
  TContext
> => {
  const mutationKey = ['createProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const createProfile = useCreateProfileHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useCreateProfileHook>>>,
    { data: BodyType<CreateProfileRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProfileMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useCreateProfileHook>>>
>;
export type CreateProfileMutationBody = BodyType<CreateProfileRequest>;
export type CreateProfileMutationError = ErrorType<void>;

/**
 * @summary Create profile
 */
export const useCreateProfile = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<ReturnType<typeof useCreateProfileHook>>>,
      TError,
      { data: BodyType<CreateProfileRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useCreateProfileHook>>>,
  TError,
  { data: BodyType<CreateProfileRequest> },
  TContext
> => {
  return useMutation(useCreateProfileMutationOptions(options), queryClient);
};

/**
 * @summary Get profile by id
 */
export const useGetProfileByIdHook = () => {
  const getProfileById = useCustomAxiosInstance<Profile>();

  return useCallback(
    (profileId: string, signal?: AbortSignal) => {
      return getProfileById({
        url: `/api/profiles/${profileId}`,
        method: 'GET',
        signal,
      });
    },
    [getProfileById]
  );
};

export const getGetProfileByIdQueryKey = (profileId: string) => {
  return [`/api/profiles/${profileId}`] as const;
};

export const useGetProfileByIdQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
  TError = ErrorType<void>,
>(
  profileId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetProfileByIdQueryKey(profileId);

  const getProfileById = useGetProfileByIdHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>
  > = ({ signal }) => getProfileById(profileId, signal);

  return {
    queryKey,
    queryFn,
    enabled: profileId !== null && profileId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProfileByIdQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>
>;
export type GetProfileByIdQueryError = ErrorType<void>;

export function useGetProfileById<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
  TError = ErrorType<void>,
>(
  profileId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfileById<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
  TError = ErrorType<void>,
>(
  profileId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfileById<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
  TError = ErrorType<void>,
>(
  profileId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get profile by id
 */

export function useGetProfileById<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
  TError = ErrorType<void>,
>(
  profileId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileByIdHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useGetProfileByIdQueryOptions(profileId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Update profile
 */
export const useUpdateProfileHook = () => {
  const updateProfile = useCustomAxiosInstance<Profile>();

  return useCallback(
    (
      profileId: string,
      updateProfileRequest: BodyType<UpdateProfileRequest>,
      signal?: AbortSignal
    ) => {
      return updateProfile({
        url: `/api/profiles/${profileId}`,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        data: updateProfileRequest,
        signal,
      });
    },
    [updateProfile]
  );
};

export const useUpdateProfileMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useUpdateProfileHook>>>,
    TError,
    { profileId: string; data: BodyType<UpdateProfileRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useUpdateProfileHook>>>,
  TError,
  { profileId: string; data: BodyType<UpdateProfileRequest> },
  TContext
> => {
  const mutationKey = ['updateProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const updateProfile = useUpdateProfileHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useUpdateProfileHook>>>,
    { profileId: string; data: BodyType<UpdateProfileRequest> }
  > = (props) => {
    const { profileId, data } = props ?? {};

    return updateProfile(profileId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useUpdateProfileHook>>>
>;
export type UpdateProfileMutationBody = BodyType<UpdateProfileRequest>;
export type UpdateProfileMutationError = ErrorType<void>;

/**
 * @summary Update profile
 */
export const useUpdateProfile = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<ReturnType<typeof useUpdateProfileHook>>>,
      TError,
      { profileId: string; data: BodyType<UpdateProfileRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useUpdateProfileHook>>>,
  TError,
  { profileId: string; data: BodyType<UpdateProfileRequest> },
  TContext
> => {
  return useMutation(useUpdateProfileMutationOptions(options), queryClient);
};

/**
 * @summary Delete profile
 */
export const useDeleteProfileHook = () => {
  const deleteProfile = useCustomAxiosInstance<void>();

  return useCallback(
    (profileId: string, signal?: AbortSignal) => {
      return deleteProfile({
        url: `/api/profiles/${profileId}`,
        method: 'DELETE',
        signal,
      });
    },
    [deleteProfile]
  );
};

export const useDeleteProfileMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useDeleteProfileHook>>>,
    TError,
    { profileId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useDeleteProfileHook>>>,
  TError,
  { profileId: string },
  TContext
> => {
  const mutationKey = ['deleteProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const deleteProfile = useDeleteProfileHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useDeleteProfileHook>>>,
    { profileId: string }
  > = (props) => {
    const { profileId } = props ?? {};

    return deleteProfile(profileId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProfileMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useDeleteProfileHook>>>
>;

export type DeleteProfileMutationError = ErrorType<void>;

/**
 * @summary Delete profile
 */
export const useDeleteProfile = <TError = ErrorType<void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<ReturnType<typeof useDeleteProfileHook>>>,
      TError,
      { profileId: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useDeleteProfileHook>>>,
  TError,
  { profileId: string },
  TContext
> => {
  return useMutation(useDeleteProfileMutationOptions(options), queryClient);
};
