/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Kickstart API
 * The Kickstart API description
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { useCallback } from 'react';

import { useCustomAxiosInstance } from './instance';
import type { ErrorType, BodyType } from './instance';
export interface LoginRequest {
  /** The users email */
  username: string;
  /** The users password */
  password: string;
}

export interface LoginResponse {
  /** The users access token */
  access_token: string;
  /** The users email */
  username: string;
}

export interface ProfileResponse {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  role: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  createdAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  updatedAt: string;
}

export type HealthControllerCheck200Status =
  (typeof HealthControllerCheck200Status)[keyof typeof HealthControllerCheck200Status];

export const HealthControllerCheck200Status = {
  ok: 'ok',
  degraded: 'degraded',
} as const;

/**
 * @nullable
 */
export type HealthControllerCheck200Info = {
  [key: string]: {
    status: 'up' | 'degraded' | 'down';
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
} | null;

/**
 * @nullable
 */
export type HealthControllerCheck200Error = {
  [key: string]: {
    status: 'up' | 'degraded' | 'down';
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
} | null;

export type HealthControllerCheck200DetailsStatus =
  (typeof HealthControllerCheck200DetailsStatus)[keyof typeof HealthControllerCheck200DetailsStatus];

export const HealthControllerCheck200DetailsStatus = {
  up: 'up',
  degraded: 'degraded',
  down: 'down',
} as const;

export type HealthControllerCheck200Details = {
  [key: string]: {
    status: HealthControllerCheck200DetailsStatus;
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
};

export type HealthControllerCheck200 = {
  status?: HealthControllerCheck200Status;
  /** @nullable */
  info?: HealthControllerCheck200Info;
  /** @nullable */
  error?: HealthControllerCheck200Error;
  details?: HealthControllerCheck200Details;
};

export type HealthControllerCheck503Status =
  (typeof HealthControllerCheck503Status)[keyof typeof HealthControllerCheck503Status];

export const HealthControllerCheck503Status = {
  error: 'error',
  shutting_down: 'shutting_down',
} as const;

/**
 * @nullable
 */
export type HealthControllerCheck503Info = {
  [key: string]: {
    status: 'up' | 'degraded' | 'down';
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
} | null;

/**
 * @nullable
 */
export type HealthControllerCheck503Error = {
  [key: string]: {
    status: 'up' | 'degraded' | 'down';
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
} | null;

export type HealthControllerCheck503DetailsStatus =
  (typeof HealthControllerCheck503DetailsStatus)[keyof typeof HealthControllerCheck503DetailsStatus];

export const HealthControllerCheck503DetailsStatus = {
  up: 'up',
  degraded: 'degraded',
  down: 'down',
} as const;

export type HealthControllerCheck503Details = {
  [key: string]: {
    status: HealthControllerCheck503DetailsStatus;
    /** Time the health indicator took to respond, in ms */
    responseTime?: number;
    [key: string]: unknown;
  };
};

export type HealthControllerCheck503 = {
  status?: HealthControllerCheck503Status;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const useAppControllerGetHelloHook = () => {
  const appControllerGetHello = useCustomAxiosInstance<void>();

  return useCallback(
    (signal?: AbortSignal) => {
      return appControllerGetHello({ url: `/api`, method: 'GET', signal });
    },
    [appControllerGetHello]
  );
};

export const getAppControllerGetHelloQueryKey = () => {
  return [`/api`] as const;
};

export const useAppControllerGetHelloQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetHelloQueryKey();

  const appControllerGetHello = useAppControllerGetHelloHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>
  > = ({ signal }) => appControllerGetHello(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerGetHelloQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>
>;
export type AppControllerGetHelloQueryError = ErrorType<unknown>;

export function useAppControllerGetHello<
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetHello<
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAppControllerGetHello<
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useAppControllerGetHello<
  TData = Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useAppControllerGetHelloHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useAppControllerGetHelloQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const useHealthControllerCheckHook = () => {
  const healthControllerCheck =
    useCustomAxiosInstance<HealthControllerCheck200>();

  return useCallback(
    (signal?: AbortSignal) => {
      return healthControllerCheck({
        url: `/api/health`,
        method: 'GET',
        signal,
      });
    },
    [healthControllerCheck]
  );
};

export const getHealthControllerCheckQueryKey = () => {
  return [`/api/health`] as const;
};

export const useHealthControllerCheckQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  const healthControllerCheck = useHealthControllerCheckHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>
  > = ({ signal }) => healthControllerCheck(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthControllerCheckQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>
>;
export type HealthControllerCheckQueryError =
  ErrorType<HealthControllerCheck503>;

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
  TError = ErrorType<HealthControllerCheck503>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useHealthControllerCheckHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useHealthControllerCheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary Login
 */
export const useLoginHook = () => {
  const login = useCustomAxiosInstance<LoginResponse>();

  return useCallback(
    (loginRequest: BodyType<LoginRequest>, signal?: AbortSignal) => {
      return login({
        url: `/api/auth/login`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: loginRequest,
        signal,
      });
    },
    [login]
  );
};

export const useLoginMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  const mutationKey = ['login'];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const login = useLoginHook();

  const mutationFn: MutationFunction<
    Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
    { data: BodyType<LoginRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return login(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useLoginHook>>>
>;
export type LoginMutationBody = BodyType<LoginRequest>;
export type LoginMutationError = ErrorType<unknown>;

/**
 * @summary Login
 */
export const useLogin = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
      TError,
      { data: BodyType<LoginRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<ReturnType<typeof useLoginHook>>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  return useMutation(useLoginMutationOptions(options), queryClient);
};

/**
 * @summary Get profile
 */
export const useGetProfileHook = () => {
  const getProfile = useCustomAxiosInstance<ProfileResponse>();

  return useCallback(
    (signal?: AbortSignal) => {
      return getProfile({ url: `/api/auth/profile`, method: 'GET', signal });
    },
    [getProfile]
  );
};

export const getGetProfileQueryKey = () => {
  return [`/api/auth/profile`] as const;
};

export const useGetProfileQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProfileQueryKey();

  const getProfile = useGetProfileHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>
  > = ({ signal }) => getProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProfileQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>
>;
export type GetProfileQueryError = ErrorType<void>;

export function useGetProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
          TError,
          Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get profile
 */

export function useGetProfile<
  TData = Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetProfileHook>>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = useGetProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
